### ISSUE TITLE
Docu seems to be obsolete

### ISSUE THREAD

**Issue by abstract-thinking** [Wolfant/ansible-jbossCli#4] opened 2018-08-23 16:10 UTC
Hi Wolfant,

I found you plug-in and it seems exactly what I'm looking for.

Here some feedback from the docu which I found.
All your example in the readme.md seems to be wrong.
Instead of jboss it should be jbosscli.
Further and I'm really happy is that the script supports --file is supported.
In the readme.md it's wrong that only command is mandatory. I have fortunately the choice between command and src.

Maybe you can update this. In the jbosscli.py the docu seems to be ok and brought me to the right way.

Cheers,
Markus

**Comment by Wolfant** [comment] 2018-08-23 22:07
Hi,

Thanks for review, I hope my module help you
The issue is fix on https://github.com/Wolfant/ansible-jbossCli/commit/00c6411cf63f537181eead21d2539659ca33fa6d

Cheers,

**Comment by gilcot** [comment] 2019-04-04 18:41
Please, don't forget to close the issue ;)

**Closed as completed** 2019-05-03 20:30 UTC
